### ISSUE TITLE
Typescript missing ErrorEvent type

### ISSUE THREAD

**Issue by uberwild** [timotejroiko/net-ipc#1]
In the index.d.ts file, the ErrorEvent type is missing, and it's giving me this error.

![image](https://user-images.githubusercontent.com/48020247/156666135-97e116a0-a206-43c6-8f62-79c0e0ce63c1.png)

**Comment by VascoBotelho** [comment]
I have lib: ["ES2021"]

**Comment by timotejroiko** [comment]
try with lib: ["ES2021", "DOM"]

**Comment by VascoBotelho** [comment]
It worked, thank you.
