### ISSUE TITLE
IPC overridden in latest commit

### ISSUE THREAD

**Issue by zawata** [timotejroiko/net-ipc#2]
Saw the latest commit. Appreciate the changes!

This code:
https://github.com/timotejroiko/net-ipc/blob/0388aa235acb99951e470e9f9ec31e28a97b8676/src/server.js#L65
unfortunately won't work as intended.

if listener options.port is set to undefined, node treats it as a 0 and binds to a tcp socket instead of a unix socket.
https://github.com/nodejs/node/blob/main/lib/net.js#L1588

I would have submitted a PR but it looks like you have a very particular coding style and I'm not sure how you'd want to fix this.
my fix: https://github.com/zawata/net-ipc/commit/2c83eb3f703f2621dce3f25a9776b5e9d5f0ca8a

Love the library!

**Comment by timotejroiko** [comment]
nice catch, your fix is fine, you can PR
