### ISSUE TITLE
ClientStatus enum problems

### ISSUE THREAD

**Issue by pioupia** [timotejroiko/net-ipc#6]
We can access to the `ClientStatus` value from TypeScript because of the type. But, after the compile with TSC, an error appears:
```js
if (this.client.status === net_ipc_1.ClientStatus.READY)

TypeError: Cannot read properties of undefined (reading 'READY')
```

because the `ClientStatus` values were never export.

**Comment by timotejroiko** [comment]
changed it to const enum, check if it works now `npm i timotejroiko/net-ipc`

**Comment by pioupia** [comment]
> changed it to const enum, check if it works now `npm i timotejroiko/net-ipc`

Yeah, thats work fine, thank you!
